export const checkInDeskStyles = {
  title: "mb-6 font-heading text-2xl font-semibold tracking-tight",
  grid: "grid gap-6 lg:grid-cols-2",
  scanCard: "flex flex-col items-center gap-4 py-10",
  scanHint: "text-center text-sm text-muted-foreground",
  feedbackName: "font-heading text-xl font-semibold",
  feedbackMeta: "text-sm text-muted-foreground",
  section: "mb-8",
  sectionHeader: "mb-3 flex items-center justify-between gap-2",
  sectionTitle: "font-heading text-lg font-semibold",
  liveStatus: "flex items-center gap-1.5 text-xs text-muted-foreground",
  liveDot: "h-2 w-2 rounded-full bg-status-active",
  liveDotOff: "h-2 w-2 rounded-full bg-status-expired",
  row: "flex items-center justify-between gap-4 border-b py-3 last:border-b-0",
  rowMain: "min-w-0",
  rowTitle: "truncate font-medium",
  rowMeta: "text-sm text-muted-foreground",
  empty: "text-sm text-muted-foreground",
} as const;
